version: '3.8'

services:
  postgres:
    env_file:
      - .env.docker
    image: postgres:16-alpine
    container_name: cloudbeats-postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudbeats"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cloudbeats-network

  minio:
    image: minio/minio:latest
    container_name: cloudbeats-minio
    env_file:
      - .env.docker
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - cloudbeats-network

  minio-init:
    image: minio/mc:latest
    container_name: cloudbeats-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb cloudbeats-docker --ignore-existing;
      /usr/bin/mc version enable cloudbeats-docker;
      exit 0;
      "
    networks:
      - cloudbeats-network

  app:
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudbeats-app
    environment:
      STORAGE_MINIO_ENDPOINT: http://minio:9000
      STORAGE_MINIO_BUCKET_NAME: cloudbeats-docker
    depends_on:
      postgres:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    networks:
      - cloudbeats-network

volumes:
  postgres_data:
  minio_data:

networks:
  cloudbeats-network:
    driver: bridge
