BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS oauth2_authorized_client (
  client_registration_id varchar(100) NOT NULL,
  principal_name varchar(200) NOT NULL,
  access_token_type varchar(100) NOT NULL,
  access_token_value bytea NOT NULL,
  access_token_issued_at timestamp NOT NULL,
  access_token_expires_at timestamp NOT NULL,
  access_token_scopes varchar(1000) DEFAULT NULL,
  refresh_token_value bytea DEFAULT NULL,
  refresh_token_issued_at timestamp DEFAULT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (client_registration_id, principal_name)
);

-- Per-user albums (replaces the old bigint 'album' table)
CREATE TABLE IF NOT EXISTS public.albums
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT albums_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_album_per_user UNIQUE (name, user_id)
);

CREATE TABLE IF NOT EXISTS public.application_user
(
    id uuid NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT application_user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.artists
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT artists_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_artist_per_user UNIQUE (name, user_id)
);

CREATE TABLE IF NOT EXISTS public.media_storage_account
(
    id uuid NOT NULL,
    access_token text COLLATE pg_catalog."default",
    account_name character varying(255) COLLATE pg_catalog."default",
    account_user_id character varying(255) COLLATE pg_catalog."default",
    provider character varying(255) COLLATE pg_catalog."default",
    refresh_token text COLLATE pg_catalog."default",
    token_expires_at timestamp(6) without time zone,
    token_issued_utc timestamp(6) without time zone,
    user_id uuid NOT NULL,
    CONSTRAINT media_storage_account_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.oauth2_authorized_client
(
    client_registration_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    principal_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    access_token_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    access_token_value bytea NOT NULL,
    access_token_issued_at timestamp without time zone NOT NULL,
    access_token_expires_at timestamp without time zone NOT NULL,
    access_token_scopes character varying(1000) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    refresh_token_value bytea,
    refresh_token_issued_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT oauth2_authorized_client_pkey PRIMARY KEY (client_registration_id, principal_name)
);

CREATE TABLE IF NOT EXISTS public.playlist_songs
(
    playlist_id bigint NOT NULL,
    file_external_id character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    file_provider character varying(255) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.playlists
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    owner_id uuid NOT NULL,
    CONSTRAINT playlists_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.albums
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(255) NOT NULL,
    user_id uuid NOT NULL,

    CONSTRAINT albums_pkey PRIMARY KEY (id),
    CONSTRAINT fk_albums_user_id FOREIGN KEY (user_id)
        REFERENCES public.application_user (id)
        ON DELETE CASCADE,

    CONSTRAINT uniq_album_per_user UNIQUE (name, user_id)
);

CREATE INDEX IF NOT EXISTS idx_albums_user_id ON public.albums (user_id);

CREATE TABLE IF NOT EXISTS public.stored_file_metadata
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255),
    album_cover_url character varying(1024),
    preview_url character varying(255),
    duration integer,
    year integer,
    album_id uuid,
    CONSTRAINT stored_file_metadata_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stored_files
(
    external_id character varying(1024) NOT NULL,
    provider character varying(255) NOT NULL,
    metadata_id uuid,
    owner_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    created_at timestamp(6) with time zone,
    last_synced timestamp(6) with time zone,
    last_modified timestamp(6) with time zone,
    folder_external_id character varying(1024),
    preview_url character varying(1024),
    folder_provider character varying(255),
    search_text text,
    CONSTRAINT stored_files_pkey PRIMARY KEY (external_id, provider),
    CONSTRAINT fk_stored_files_metadata
        FOREIGN KEY (metadata_id) REFERENCES public.stored_file_metadata(id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.stored_file_metadata_artists
(
    metadata_id uuid NOT NULL,
    artist_id uuid NOT NULL,
    CONSTRAINT stored_file_metadata_artists_pkey PRIMARY KEY (metadata_id, artist_id)
);

CREATE TABLE IF NOT EXISTS public.stored_file_metadata_genres
(
    metadata_id uuid NOT NULL,
    genre character varying(255) COLLATE pg_catalog."default"
);

CREATE INDEX IF NOT EXISTS idx_sf_search_text_trgm
ON public.stored_files USING GIN(search_text gin_trgm_ops);

-- Trigger: keep search_text in sync using stored_file_metadata_artists
CREATE OR REPLACE FUNCTION update_stored_file_search_text()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- We join artists via the metadata_id stored directly on the file (NEW)
    NEW.search_text := lower(coalesce(NEW.name, '') || ' ' || coalesce((
        SELECT string_agg(a.name, ' ')
        FROM artists a
        INNER JOIN stored_file_metadata_artists sfma ON sfma.artist_id = a.id
        WHERE sfma.metadata_id = NEW.metadata_id
    ), ''));
    RETURN NEW;
END;
$$;

-- Trigger remains BEFORE INSERT OR UPDATE
CREATE OR REPLACE TRIGGER trg_stored_files_search_text
BEFORE INSERT OR UPDATE OF name, metadata_id -- Added metadata_id as a trigger column
ON public.stored_files
FOR EACH ROW
EXECUTE FUNCTION update_stored_file_search_text();

CREATE OR REPLACE FUNCTION update_search_text_on_artist_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- Update files where the metadata_id is linked to the modified artist
    UPDATE stored_files sf
    SET search_text = lower(coalesce(sf.name, '') || ' ' || coalesce((
        SELECT string_agg(a.name, ' ')
        FROM artists a
        INNER JOIN stored_file_metadata_artists sfma ON sfma.artist_id = a.id
        WHERE sfma.metadata_id = sf.metadata_id
    ), ''))
    WHERE sf.metadata_id IN (
        SELECT metadata_id
        FROM stored_file_metadata_artists
        WHERE artist_id = NEW.id
    );
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_artists_search_text
AFTER UPDATE OF name ON public.artists
FOR EACH ROW EXECUTE FUNCTION update_search_text_on_artist_change();

CREATE OR REPLACE FUNCTION update_search_text_on_metadata_artist_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    target_metadata_id uuid;
BEGIN
    target_metadata_id := COALESCE(NEW.metadata_id, OLD.metadata_id);

    -- Find the file that points to this metadata and force an update
    UPDATE stored_files sf
    SET search_text = lower(coalesce(sf.name, '') || ' ' || coalesce((
        SELECT string_agg(a.name, ' ')
        FROM artists a
        INNER JOIN stored_file_metadata_artists sfma ON sfma.artist_id = a.id
        WHERE sfma.metadata_id = sf.metadata_id
    ), ''))
    WHERE sf.metadata_id = target_metadata_id;

    RETURN NULL;
END;
$$;

CREATE OR REPLACE TRIGGER trg_sfma_link_change
AFTER INSERT OR UPDATE OR DELETE ON public.stored_file_metadata_artists
FOR EACH ROW EXECUTE FUNCTION update_search_text_on_metadata_artist_change();

CREATE TABLE IF NOT EXISTS public.stored_folders
(
    external_id character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    provider character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) with time zone,
    last_synced timestamp(6) with time zone,
    last_modified timestamp(6) with time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    path character varying(1024) COLLATE pg_catalog."default",
    owner_id uuid NOT NULL,
    parent_external_id character varying(1024) COLLATE pg_catalog."default",
    parent_provider character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT stored_folders_pkey PRIMARY KEY (external_id, provider)
);

-- Foreign keys
ALTER TABLE IF EXISTS public.albums
    ADD CONSTRAINT fk_albums_user FOREIGN KEY (user_id)
    REFERENCES public.application_user (id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.artists
    ADD CONSTRAINT fkro0djvtwl7u758gbg49ooeccx FOREIGN KEY (user_id)
    REFERENCES public.application_user (id) ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.media_storage_account
    ADD CONSTRAINT fklrsvuid9xsnkqxqob03v8fiv2 FOREIGN KEY (user_id)
    REFERENCES public.application_user (id) ON DELETE NO ACTION;

--ALTER TABLE IF EXISTS public.stored_files
--    ADD CONSTRAINT fk_sf_album FOREIGN KEY (album_id)
--    REFERENCES public.albums (id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.stored_files
    ADD CONSTRAINT fkl41rfraef9x6crmv7y1g43or2 FOREIGN KEY (owner_id)
    REFERENCES public.application_user (id) ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.stored_files
    ADD CONSTRAINT fk9koy37jmr8paip308l3j2tchj FOREIGN KEY (folder_external_id, folder_provider)
    REFERENCES public.stored_folders (external_id, provider) ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.stored_file_artists
    ADD CONSTRAINT fk_sfa_file FOREIGN KEY (file_external_id, file_provider)
    REFERENCES public.stored_files (external_id, provider) ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.stored_file_artists
    ADD CONSTRAINT fk_sfa_artist FOREIGN KEY (artist_id)
    REFERENCES public.artists (id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.stored_file_genres
    ADD CONSTRAINT fk_sfg_file FOREIGN KEY (file_external_id, file_provider)
    REFERENCES public.stored_files (external_id, provider) ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.playlist_songs
    ADD CONSTRAINT fk5nojrf8x0k7khb91palpgeuhc FOREIGN KEY (file_external_id, file_provider)
    REFERENCES public.stored_files (external_id, provider) ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.playlist_songs
    ADD CONSTRAINT fkqfutupgj870d2k31ldxqqwr8w FOREIGN KEY (playlist_id)
    REFERENCES public.playlists (id) ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.playlists
    ADD CONSTRAINT fkjuunodoxjph37px48vomc6a8r FOREIGN KEY (owner_id)
    REFERENCES public.application_user (id) ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.stored_folders
    ADD CONSTRAINT fkhrirr26vaj7lnechyras2b0m9 FOREIGN KEY (parent_external_id, parent_provider)
    REFERENCES public.stored_folders (external_id, provider) ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.stored_folders
    ADD CONSTRAINT fktaboxx1yn5vyh7qegagsjtrnh FOREIGN KEY (owner_id)
    REFERENCES public.application_user (id) ON DELETE NO ACTION;

END;


