-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.album
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT album_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.album_artists
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT album_artists_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.application_user
(
    id uuid NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT application_user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.artists
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT artists_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_artist_per_user UNIQUE (name, user_id)
);

CREATE TABLE IF NOT EXISTS public.audio_file_metadata
(
    file_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_hash character varying(255) COLLATE pg_catalog."default",
    last_modified timestamp(6) without time zone,
    preview_url character varying(255) COLLATE pg_catalog."default",
    album character varying(255) COLLATE pg_catalog."default",
    album_cover_url character varying(255) COLLATE pg_catalog."default",
    duration double precision NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    year integer,
    CONSTRAINT audio_file_metadata_pkey PRIMARY KEY (file_id)
);

CREATE TABLE IF NOT EXISTS public.audio_file_metadata_album_artists
(
    audio_file_metadata_file_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    album_artists character varying(255) COLLATE pg_catalog."default",
    album_artists_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    album_artists_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.audio_file_metadata_genres
(
    audio_file_metadata_file_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    genres character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.media_storage_account
(
    id uuid NOT NULL,
    access_token text COLLATE pg_catalog."default",
    account_name character varying(255) COLLATE pg_catalog."default",
    account_user_id character varying(255) COLLATE pg_catalog."default",
    provider character varying(255) COLLATE pg_catalog."default",
    refresh_token text COLLATE pg_catalog."default",
    token_expires_at timestamp(6) without time zone,
    token_issued_utc timestamp(6) without time zone,
    user_id uuid NOT NULL,
    CONSTRAINT media_storage_account_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.oauth2_authorized_client
(
    client_registration_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    principal_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    access_token_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    access_token_value bytea NOT NULL,
    access_token_issued_at timestamp without time zone NOT NULL,
    access_token_expires_at timestamp without time zone NOT NULL,
    access_token_scopes character varying(1000) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    refresh_token_value bytea,
    refresh_token_issued_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT oauth2_authorized_client_pkey PRIMARY KEY (client_registration_id, principal_name)
);

CREATE TABLE IF NOT EXISTS public.playlist_songs
(
    playlist_id bigint NOT NULL,
    file_external_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_provider character varying(255) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.playlists
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    owner_id uuid NOT NULL,
    CONSTRAINT playlists_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stored_files
(
    external_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    provider character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) with time zone,
    last_synced timestamp(6) with time zone,
    last_modified timestamp(6) with time zone,
    metadata_json jsonb,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    preview_url character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    folder_external_id character varying(255) COLLATE pg_catalog."default",
    folder_provider character varying(255) COLLATE pg_catalog."default",
    owner_id uuid NOT NULL,
    search_text text,
    CONSTRAINT stored_files_pkey PRIMARY KEY (external_id, provider)
);

-- 1. Ensure extension is active
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 3. The Performant Index
CREATE INDEX IF NOT EXISTS idx_sf_search_text_trgm
ON public.stored_files USING GIN(search_text gin_trgm_ops);

-- 4. Simplified Trigger Function
CREATE OR REPLACE FUNCTION update_stored_file_search_text()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.search_text := lower(coalesce(NEW.name, '') || ' ' || coalesce((
        SELECT string_agg(a.name, ' ')
        FROM artists a
        INNER JOIN audio_file_metadata_album_artists afma
            ON afma.album_artists_id = a.id
        WHERE afma.audio_file_metadata_file_id = NEW.external_id
    ), ''));
    RETURN NEW;
END;
$$;

-- 5. Attach Trigger
CREATE OR REPLACE TRIGGER trg_stored_files_search_text
BEFORE INSERT OR UPDATE OF name, metadata_json
ON public.stored_files
FOR EACH ROW
EXECUTE FUNCTION update_stored_file_search_text();

CREATE TABLE IF NOT EXISTS public.stored_folders
(
    external_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    provider character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) with time zone,
    last_synced timestamp(6) with time zone,
    last_modified timestamp(6) with time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    path character varying(1024) COLLATE pg_catalog."default",
    owner_id uuid NOT NULL,
    parent_external_id character varying(255) COLLATE pg_catalog."default",
    parent_provider character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT stored_folders_pkey PRIMARY KEY (external_id, provider)
);

ALTER TABLE IF EXISTS public.album_artists
    ADD CONSTRAINT fklngnuy6wn7olc16w9br3k23rq FOREIGN KEY (user_id)
    REFERENCES public.application_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.artists
    ADD CONSTRAINT fkro0djvtwl7u758gbg49ooeccx FOREIGN KEY (user_id)
    REFERENCES public.application_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audio_file_metadata_album_artists
    ADD CONSTRAINT fk2id79j9olom3mpo7rlnodhub FOREIGN KEY (album_artists_id)
    REFERENCES public.album_artists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audio_file_metadata_album_artists
    ADD CONSTRAINT fk4sv17rf1gt6b4ko1k6xubu5w5 FOREIGN KEY (audio_file_metadata_file_id)
    REFERENCES public.audio_file_metadata (file_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audio_file_metadata_album_artists
    ADD CONSTRAINT fkmax7gny3jx15u2otyamaniuo4 FOREIGN KEY (album_artists_id)
    REFERENCES public.artists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audio_file_metadata_genres
    ADD CONSTRAINT fkjack52tpe9d8g439lwxjgknam FOREIGN KEY (audio_file_metadata_file_id)
    REFERENCES public.audio_file_metadata (file_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_storage_account
    ADD CONSTRAINT fklrsvuid9xsnkqxqob03v8fiv2 FOREIGN KEY (user_id)
    REFERENCES public.application_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.playlist_songs
    ADD CONSTRAINT fk5nojrf8x0k7khb91palpgeuhc FOREIGN KEY (file_external_id, file_provider)
    REFERENCES public.stored_files (external_id, provider) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.playlist_songs
    ADD CONSTRAINT fkqfutupgj870d2k31ldxqqwr8w FOREIGN KEY (playlist_id)
    REFERENCES public.playlists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.playlists
    ADD CONSTRAINT fkjuunodoxjph37px48vomc6a8r FOREIGN KEY (owner_id)
    REFERENCES public.application_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stored_files
    ADD CONSTRAINT fk9koy37jmr8paip308l3j2tchj FOREIGN KEY (folder_external_id, folder_provider)
    REFERENCES public.stored_folders (external_id, provider) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stored_files
    ADD CONSTRAINT fkl41rfraef9x6crmv7y1g43or2 FOREIGN KEY (owner_id)
    REFERENCES public.application_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stored_folders
    ADD CONSTRAINT fkhrirr26vaj7lnechyras2b0m9 FOREIGN KEY (parent_external_id, parent_provider)
    REFERENCES public.stored_folders (external_id, provider) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stored_folders
    ADD CONSTRAINT fktaboxx1yn5vyh7qegagsjtrnh FOREIGN KEY (owner_id)
    REFERENCES public.application_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;